### ISSUE TITLE
Configurable iternal port please

### ISSUE THREAD

**Issue by ckramer** [Jafea7/ctbrec-debian#6]
I have another container using 8080 and getting fatal "port already in use" when starting.
in internal config there's `"httpPort" : 8080,` but other places its's hardcoded it seems.
Thank you.

**Comment by Jafea7** [comment]
Why do you think it isn't configurable?

Run the container, stop the container, edit the server.json, (under the version directory), edit your docker command/compose.

**Comment by Jafea7** [comment]
I'm not sure where you get the idea from that you rebuild the image:

- run the container
- stop the container
- edit the config file, `/app/config/<version>/server.json` for whatever port(s) you want, e.g. `"httpPort" : 58080,`
- edit your `docker-compose.yml` so that the container ports, (not host ports), match in the above step, i.e. `- 8080:58080`

**Comment by ckramer** [comment]
> I'm not sure where you get the idea from that you rebuild the image

I think because in Dockerfile it has hardcoded:
```
EXPOSE 8080 8443
```
If I need to change these too, then rebuild is needed ?

**Comment by Jafea7** [comment]
What's your docker-compose.yml because I've got no problem running multiple CTBRec containers doing what I said above.

**Comment by ckramer** [comment]
This is fantastic. I didn't know you can pass velues like that. 
Thank you! I'll try it.  
Maybe good to include such example in documentation 😋

**Comment by ckramer** [comment]
Hav you tried accessing without 8443/ssl? No matter what I do it wants to redirect and serve from 8443.
I think I also need
``` 
SRVURL=http://127.0.0.1:8080
```
in compose yml

**Comment by Jafea7** [comment]
Read the README for the repo, then you'll know why it redirects to SSL and what SRVURL is used for.

At the moment there is no issue to deal with regarding the repo, (apart from the Python API needing an update).

**Comment by ckramer** [comment]
> Read the README for the repo, then you'll know why it redirects to SSL and what SRVURL is used for.
> 
> At the moment there is no issue to deal with regarding the repo, (apart from the Python API needing an update).

Yes I'm asking because I'v read whole README and there's no mention that something is supposed to redirect 8080 to 8443.  It only states that you can use either.

**Comment by Jafea7** [comment]
<https://www.cloudflare.com/en-au/learning/ssl/what-is-ssl/>

> Secure Sockets Layer (SSL) is a security protocol that provides privacy, authentication, and integrity to Internet communications. SSL eventually evolved into Transport Layer Security (TLS).

<https://github.com/Jafea7/ctbrec-debian?tab=readme-ov-file#default-web-interface-access>

**"transportLayerSecurity": true**

**Comment by ckramer** [comment]
can I override it to false in docker compose? 
Or do I need to run container open shell edit server.json ?
